name: Result for tests

on: [repository_dispatch]

jobs:
  my-result:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        if: github.event.action == 'my-result'
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
          echo "Payload:  '${{ toJSON(github.event.client_payload) }}'"
      - name: Handle Results Tests
        if: github.event.action == 'my-result'
        run: |
          echo "Test result received"
          echo "Repository '${{ github.event.client_payload.repository }}' "
          var result = ${{github.event.client_payload.result}}
          if ["$result" == "failure"]; then
            echo "Result: '$result'"
            exit 1
          else
            echo "Result: '$result'"
          fi