name: Remote Dispatch Component-Test Action Responder

on: [repository_dispatch]

jobs:
  my-result:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
          echo "Event Type '${{ github.event.event_type }}'"
      - name: Handle Results Tests
        run: |
          echo "Test result received"
          echo "Repository '${{ github.event.client_payload.repository }}' "
          echo "Result: '${{ github.event.client_payload.result }}'"