name: Results for Search

on:
  repository_dispatch:
    types: [my-search-result]

jobs:
  my-search-result:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
          echo "Payload:  '${{ toJSON(github.event.client_payload) }}'"

      - name: Display Search Results
        run: |
          echo "Search results received for:"
          echo "Repository: '${{ github.event.client_payload.repository }}' "
          echo "Found results: '${{ github.event.client_payload.foundResults }}' "