name: Result for tests

on:
  repository_dispatch:
    types: [ my-result ]

jobs:
  my-result:
    name: "Search result for: ${{ github.event.client_payload.search-string }}"
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
          echo "Payload:  '${{ toJSON(github.event.client_payload) }}'"

      - name: Display Result
        run: |
          echo "Test result received"
          echo "Repository: '${{ github.event.client_payload.repository }}' "
          echo "Error results: '${{ github.event.client_payload.resultUrl }}' "

      - name: Handle results failures
        if: github.event.action == 'my-result' && github.event.client_payload.result != 'success'
        run:  exit 1