name: Trigger Component Tests

on:
  #push:
  schedule:
    - cron: '0 12 * * *'
  #repository_dispatch:
  workflow_dispatch:
    inputs:
      test-type:
        type: choice
        description: Which tests
        default: component/integration
        options:
          - all
          - junit
          - component/integration
        required: true

jobs:
  dispatch:
    strategy:
      matrix:
        repo: ['fransah/trigger1', 'fransah/trigger2']
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Test Repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TRIGGER_TEST1 }}
          repository: ${{ matrix.repo }}
          event-type: do-component-test
          client-payload: '{ "repository": "${{github.repository}}", "type-test": "${{ github.event.inputs.test-type }}"  }'