name: Trigger Tests

on:
  #push:
  schedule:
    - cron: '0 12 * * *'
  #repository_dispatch:
  workflow_dispatch:

jobs:
  dispatch:
    strategy:
      matrix:
        repo: ['fransah/trigger1', 'fransah/trigger2']
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Test Repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TRIGGER_TEST1 }}
          repository: ${{ matrix.repo }}
          event-type: do-component-test
          client-payload: '{ "repository": "${{github.repository}}" }'